server:
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: BINexus_backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_db
    username: root
    password: root
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
aliyun:
  Key: sk-5d9ed2f75671417f9708ff63defbfc0c
  model: qwen-max